name: Simple Workflow

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs today at 5:52 PM IST (12:22 PM UTC)

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Current Date
        run: date
