name: Simple Workflow

on:
  schedule:
    - cron: '22 12 15 4 *'  # Runs today at 5:52 PM IST (12:22 PM UTC)
  workflow_dispatch:   # Allows manual trigger

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Current Date
        run: date
