name: Simple Environment Workflow

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: "Select environment"
        required: true
        default: "demo"

jobs:
  test-environment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Print Environment
        run: echo "Using environment"
